api_settings:
  token_endpoint: "https://icdaccessmanagement.who.int/connect/token"
  client_id: "40cb6baa-6644-49fd-9497-de3651964921_c3c4b06d-9ec4-492c-ac6f-9c94c2ae0329"
  client_secret: "zj5f4S0Q357RB5DYdHJiWOWUtIAn5shKcRAYSyX2Ngw="
  scope: "icdapi_access"
  grant_type: "client_credentials"
  entity_url: "https://id.who.int/icd/entity/"

scrape_settings:
  urls: ["https://id.who.int/icd/release/11/version/mms/","https://id.who.int/icd/entity/"]
  main_entity: "455013390"
  #main_entity: "1435254666"
  output_dir: "./data"
  raw_output: "data/version/raw"